name: "Lint PR"

on:
  # pull_request is only for initial submission into the repo
  # we can delete this in a follow-up PR
  pull_request: 
    types:
      - opened
      - edited
      - reopened
  pull_request_target: 
    types:
      - opened
      - edited
      - reopened

jobs:
  validate_pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      statuses: write
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
          requireScope: false
