name: PR labeler

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validate-pr-title:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commit Validation
        uses:  ytanikin/pr-conventional-commits@1.4.0
        with:
         task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
         custom_labels: '{"feat": "enhancement", "fix": "fix", "docs": "documentation", "test": "test", "ci": "test", "refactor": "chore", "chore": "chore", "revert": "revert"}'
